#!/bin/sh




background="$(grep background /usr/share/sddm/themes/breeze/theme.conf.user | cut -f2 -d=)"

if [ -e "$background" ]; then
    feh --bg-scale "$background" &
else
    feh --bg-scale "$(grep background /usr/share/sddm/themes/breeze/theme.conf.user | cut -f2 -d= | sed 's|^|/usr/share/wallpapers/|g')" &
fi

sleep 2
killall feh
